# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2a0ef99f-674f-4fee-a4e7-5ce378f7506e";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@nix" ];
    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/a21aa17d-cf53-4e92-bc64-fcb5b8c691de";
#      fsType = "ext4";
#    };


  fileSystems."/storage" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@storage" "autodefrag" "space_cache" "discard" ];

    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2a0ef99f-674f-4fee-a4e7-5ce378f7506e";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@home" "autodefrag" "space_cache" "discard" ];

    };


  fileSystems."/storage/attic" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@attic" "autodefrag" "space_cache" "discard" ];

    };

  fileSystems."/storage/audio" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@audio" "autodefrag" "space_cache" "discard" ];

    };

  fileSystems."/storage/backups" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@backups" "autodefrag" "space_cache" "discard" ];

    };

  fileSystems."/storage/books" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@books" "autodefrag" "space_cache" "discard" ];

    };


  fileSystems."/storage/games" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@games" "autodefrag" "space_cache" "discard" ];

    };

  fileSystems."/storage/incoming" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@incoming" "autodefrag" "space_cache" "discard" ];

    };

  fileSystems."/storage/misc" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@misc" "autodefrag" "space_cache" "discard" ];

    };

   fileSystems."/storage/movies" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@movies" "autodefrag" "space_cache" "discard" ];

    };

  fileSystems."/storage/music" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@music" "autodefrag" "space_cache" "discard" ];

    };

   fileSystems."/storage/software" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@software" "autodefrag" "space_cache" "discard" ];

    };


   fileSystems."/data" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "autodefrag" "space_cache" "discard" ];

    };


  fileSystems."/home/liquuid/Music" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@music" "autodefrag" "space_cache" "discard" ];

    };


  fileSystems."/home/liquuid/Downloads" =
    { device = "/dev/disk/by-uuid/711e078a-32d3-4c0f-bee2-6bb0a3ec3f38";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@incoming" "autodefrag" "space_cache" "discard" ];

    };


  fileSystems."/home/liquuid/.local/share/Steam" =
    { device = "/dev/disk/by-uuid/47f4a9d3-175a-457b-9668-45d9ab66b63b";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=@steam" "autodefrag" "space_cache" "discard" ];

    };
  

  fileSystems."/home/liquuid/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps" =
    { device = "/home/liquuid/.local/share/Steam/steamapps";
      options = [ "bind" ];

    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5D64-4714";
      fsType = "vfat";
    };

  swapDevices = [ 
     { device = "/dev/nvme0n1p3"; } 
     { device = "/dev/nvme0n1p5"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp27s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp28s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
