# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e8c6f926-102e-4c58-be26-c9d08c88a2ef";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" ];
    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/955c688f-66bd-478c-8260-efa6c4138059";
#      fsType = "ext4";
#    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F908-D4D8";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e8c6f926-102e-4c58-be26-c9d08c88a2ef";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };
  fileSystems."/srv" =
    { device = "/dev/data/srv";
      fsType = "xfs";
      options = [ "noatime" ];
    };
  fileSystems."/srv-240" =
    { device = "/dev/disk/by-uuid/003b92fd-f275-41ad-b591-6bb69a179aa5";
      fsType = "btrfs";
      options = [ "compress=zstd" "autodefrag" ];
    };

  fileSystems."/home/liquuid/Downloads" =
    { device = "/dev/data/downloads";
      fsType = "ext4";
      options = [ "noatime" ];
    };
  fileSystems."/home/liquuid/Downloads/.@" =
    { device = "/dev/data/notwork";
      fsType = "ext4";
      options = [ "noatime" ];
   };
  #fileSystems."/storage/home-hydra" =
  #  { device = "192.168.0.111:/mnt/storage/home-hydra";
  #    fsType = "nfs";
  #    options = [ "x-systemd.automount" "noauto" "x-systemd.mount-timeout=90" "async"]; 
  #  };

  fileSystems."/home/liquuid/Music" =
    { device = "192.168.0.111:/mnt/storage/music";
      fsType = "nfs";
      options = [ "x-systemd.automount" "noauto" "x-systemd.mount-timeout=90" "async" ];
    };
  #fileSystems."/images" =
  #  { 
  #    device = "images";
  #    fsType = "zfs";
  #    options = ["zfsutils"];

  #  };
  #fileSystems."/storage/storage-vm" =
  #  { device = "192.168.0.111:/mnt/storage/storage-vm";
  #    fsType = "nfs";
  #    options = [ "x-systemd.automount" "noauto" "x-systemd.mount-timeout=90"]; 
  #  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp36s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp35s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
