# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5c1bdce3-f126-4016-953c-d7ac4efb4443";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/43db1d82-bd1b-4d6e-90e5-b9b8b919e961"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
